// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB25-Oiu7Gomu5AGvMXnV0sFw7G0Urxon8',
    appId: '1:818545460753:web:83237346fa2e84b93693b0',
    messagingSenderId: '818545460753',
    projectId: 'smart-enterprises-d444b',
    authDomain: 'smart-enterprises-d444b.firebaseapp.com',
    storageBucket: 'smart-enterprises-d444b.firebasestorage.app',
    measurementId: 'G-MZ69YH2VEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy0mGeDAdM9kIOVkk0u-q8d5ImK03sk84',
    appId: '1:818545460753:android:176cb15fd11a11503693b0',
    messagingSenderId: '818545460753',
    projectId: 'smart-enterprises-d444b',
    storageBucket: 'smart-enterprises-d444b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfoyH4KQlqTTE9KFcQYkZelKI_v9YMuYo',
    appId: '1:818545460753:ios:ae9f004e2d1354a43693b0',
    messagingSenderId: '818545460753',
    projectId: 'smart-enterprises-d444b',
    storageBucket: 'smart-enterprises-d444b.firebasestorage.app',
    iosBundleId: 'com.example.inverterManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfoyH4KQlqTTE9KFcQYkZelKI_v9YMuYo',
    appId: '1:818545460753:ios:73714c0e5ef8e2713693b0',
    messagingSenderId: '818545460753',
    projectId: 'smart-enterprises-d444b',
    storageBucket: 'smart-enterprises-d444b.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB25-Oiu7Gomu5AGvMXnV0sFw7G0Urxon8',
    appId: '1:818545460753:web:262c7f2188d2a52f3693b0',
    messagingSenderId: '818545460753',
    projectId: 'smart-enterprises-d444b',
    authDomain: 'smart-enterprises-d444b.firebaseapp.com',
    storageBucket: 'smart-enterprises-d444b.firebasestorage.app',
    measurementId: 'G-79TJ155K0E',
  );
}
